meta_product_name: "emerald"
meta_title: "emerald - build safer"
meta_description: "Create, monitor and manage your permits to ensure worker safety, prevent delays save money across your projects."
meta_image: "banner.jpeg" # should exist in `app/assets/images/`
# twitter_account: "@product_twitter_account"   # required for Twitter Cards
